foreground #F8F8FF
background #1B1B29
selection_foreground #1B1B29
selection_background #F8F8FF
cursor #A9A7BE
cursor_text_color #FFFFFF
color0 #1B1B29
color1 #A9A7BE
color2 #2C2952
color3 #3E3A6B
color4 #A9A7BE
color5 #3E3A6B
color6 #2C2952
color7 #F8F8FF
color8 #2C2952
color9 #A9A7BE
color10 #3E3A6B
color11 #A9A7BE
color12 #A9A7BE
color13 #3E3A6B
color14 #2C2952
color15 #FFFFFF
